### ISSUE TITLE
Sum return NaN errors

### ISSUE THREAD

**Issue by eoplus** [r-quantities/quantities#1] opened 2018-04-10 11:23 UTC
I'm know the package is not yet released, so a bug report is to premature. But I wanted just to point out in case this is unnoticed:

```{r}
set_errors(1, 0) + set_errors(0, 0)
# 1(0)
set_quantities(1, 1, 0) + set_quantities(0, 1, 0)
# 1(NaN) 
```
Thanks for the awesome package =)

**Comment by Enchufa2** [comment] 2018-04-10 11:57
No bug report is too premature! Many thanks!

**Comment by Enchufa2** [comment] 2018-04-10 13:01
The problem is deeper than expected.

**Comment by Enchufa2** [comment] 2018-04-10 13:22
Now it should be fixed.

**Closed as completed** 2018-04-10 13:21 UTC
Labels: bug
